version: '3.8'
volumes:
  postgres_data:
services:
  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: evgen25max/python:3.8.5
    restart: always
    command: gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./static:/code/static/
      - ./media:/code/media/
    expose:
      - "8000"
    depends_on:
      - db
  ngnix:
    image: evgen25max/ngnix:1.19.6
    volumes:
      - ./static:/static/
      - ./media:/media/
    depends_on:
      - web
    ports:
      - "80:80"